@baseUrl = https://localhost:3001/api

### Get logged in user
GET {{baseUrl}}/account
Content-Type: application/json

### Check for logged in user
POST {{baseUrl}}/check
Content-Type: application/json

{
    "matchId": 5123274952
}

### Dev ARAM
POST {{baseUrl}}/dev
Content-Type: application/json

{
    "matchId": 5417995850,
    "summonerName": "sirlunchalot619",
    "platformId": "EUW1"
}

### Dev Summoner's Rift
POST {{baseUrl}}/dev
Content-Type: application/json

{
    "summonerName": "alice xP",
    "platformId": "EUN1",
    "matchId": 2687365610
}

### Feedback
POST {{baseUrl}}/feedback
Content-Type: application/json

{
    "discordTag": "CoachLeon#4001",
    "summonerName": "sirlunchalot619",
    "platformId": "EUW1",
    "message": "Awesome!"
}

### Get champion image
GET {{baseUrl}}/champions/69/img


### Login
POST {{baseUrl}}/login
Content-Type: application/json

{
    "summonerName": "sirlunchalot619",
    "platformId": "EUW1"
}

### Matches for logged in user
GET {{baseUrl}}/matches

### Matches for any user
GET {{baseUrl}}/matches?summonerName=sirlunchalot619&platformId=EUW1

### Matches for any user with filter
GET {{baseUrl}}/matches?summonerName=sirlunchalot619&platformId=EUW1&onlyWithTrophies=true&page=1

### Mission
GET {{baseUrl}}/mission

### Public account
GET {{baseUrl}}/public-account?summonerName=sirlunchalot619&platformId=EUW1

### Rankings by summonerName
GET {{baseUrl}}/rankings?season=11&summonerName=sirlunchalot619

### Rankings by page
GET {{baseUrl}}/rankings?season=11&page=1

### Season account
GET {{baseUrl}}/season-account?season=11

### Stats
GET {{baseUrl}}/stats

### Status
GET {{baseUrl}}/status

### Trophy stats
GET {{baseUrl}}/trophy-stats/theZombie

### Version
GET {{baseUrl}}/version